packages:
  - config
  - packages/util
  - packages/util/queue
  - packages/util/emit
  - packages/util/task
  - packages/util/async
  - packages/util/schema
  - packages/core
  - packages/runtime
  - packages/compiler
  - packages/transformer
  - packages/repl
  - packages/models/openai
  - packages/adapters/node
  - packages/adapters/node/loader
  - packages/adapters/node/quiet
  - packages/adapters/node/cli
  - packages/toolcog
  - packages/toolcog/cli
  - sandbox

catalog:
  commander: ^12.1
  typescript: ^5.5

catalogs:
  models:
    openai: ^4.52
  build:
    "@eslint/js": ^9.6
    "@rollup/plugin-node-resolve": ^15.2
    "@rollup/plugin-replace": ^5.0
    "@rollup/plugin-typescript": ^11.1
    "@types/node": ^20
    eslint: ^9.6
    eslint-plugin-jsdoc: ^48
    prettier: ^3.3
    rimraf: ^5.0
    rollup: ^4.18
    rollup-plugin-dts: ^6.1
    rollup-plugin-node-externals: ^7.1
    ts-patch: ^3.2.1
    tslib: ^2.6
    turbo: ^2.0
    typescript: ^5.5
    typescript-eslint: ^7.15
    vitest: ^1.6
