packages:
  - packages/util
  - packages/core
  - packages/runtime
  - packages/openai
  - packages/anthropic
  - packages/compiler
  - packages/repl
  - packages/node
  - packages/toolcog
  - templates/toolkit-rollup
  - sandbox

catalogs:
  runtime:
    "@anthropic-ai/sdk": ^0.28
    "@types/node": ">=20"
    commander: ^12.1
    fast-glob: ^3.3
    marked: ^14.1
    openai: ^4.67
    typescript: ^5.6.0
    yaml: ^2.5
  development:
    "@changesets/changelog-github": ^0.5
    "@changesets/cli": ^2.27
    "@eslint/js": ^9.12
    "@rollup/plugin-node-resolve": ^15.3
    "@rollup/plugin-typescript": ^12.1
    "@swc/cli": ^0.4.0
    "@swc/core": ^1.7.26
    "@swc/plugin-transform-imports": ^3.0
    "@types/node": ^22
    "@vitest/coverage-v8": ^2.1
    eslint: ^9.12
    eslint-plugin-jsdoc: ^50.3
    prettier: ^3.3
    rimraf: ^6.0
    rollup: ^4.24
    rollup-plugin-dts: ^6.1
    rollup-plugin-node-externals: ^7.1
    ts-expose-internals: ^5.5
    ts-patch: ^3.2.1
    tslib: ^2.6
    turbo: ^2.1
    typedoc: ^0.26
    typescript: 5.7.0-dev.20241001
    typescript-eslint: ^8.8
    vitest: ^2.0
  overrides:
    whatwg-url: ^14.0
