packages:
  - framework/util
  - framework/core
  - framework/runtime
  - framework/compiler
  - framework/repl
  - adapters/node
  - plugins/anthropic
  - plugins/openai
  - toolcog
  - sandbox

catalog:
  "@types/node": ">=20"
  commander: ^12.1
  fast-glob: ^3.3
  typescript: ^5.5
  yaml: ^2.5

catalogs:
  plugins:
    "@anthropic-ai/sdk": ^0.27
    openai: ^4.56
    whatwg-url: ^14.0
  build:
    "@eslint/js": ^9.9
    "@rollup/plugin-node-resolve": ^15.2
    "@rollup/plugin-replace": ^5.0
    "@rollup/plugin-typescript": ^11.1
    "@types/node": ^22
    eslint: ^9.9
    eslint-plugin-jsdoc: ^50.2
    prettier: ^3.3
    rimraf: ^6.0
    rollup: ^4.21
    rollup-plugin-dts: ^6.1
    rollup-plugin-node-externals: ^7.1
    ts-expose-internals: ^5.5
    ts-patch: ^3.2.1
    tslib: ^2.6
    turbo: ^2.0
    typescript: ^5.5
    typescript-eslint: ^8.3
    vitest: ^2.0
